### ISSUE TITLE
Feature Request: Open the diffs in VS Code for the Pull Request

### ISSUE THREAD

**Issue by bgates-mc** [KnisterPeter/vscode-github#273]
Basically emulating the functionality of this page: https://github.com/KnisterPeter/vscode-github/pull/263/files

VS Code already has this built in for your local changes vs the branch on the Source Control tab.

This would help with doing code reviews.

EDIT: Git Lens has a couple of compare commands that you can look at for reference. (Comparing different commits.)

**Comment by danehammer** [comment]
I went looking for this today as well. This seems like the extension to add it to and it looks like the [GitHub API][api] enables it to be done. I would like to drive my entire pull request code review flow from VSCode. 

[api]: https://developer.github.com/v3/pulls/comments/#create-a-comment

**Comment by KnisterPeter** [comment]
Thanks for the idea.
Duplicates #103

**Comment by rattrayalex-stripe** [comment]
Any update here? Could really change a lot of peoples' workflows.

**Comment by KnisterPeter** [comment]
Not until now. Lately I have less spare time to spend.

**Comment by rattrayalex-stripe** [comment]
Cool, no worries!

**Comment by gytibor** [comment]
I would also really like this feature a lot, because I'm doing this type of workflow manually copying files from the pull request into destination branch, so I can use VS Code for the review. 
Here is a nice quick solution for getting the pull request changes into your branch:
https://coderwall.com/p/6aw72a/creating-patch-from-github-pull-request
This might be a easier solution than the complete GitHub API integration.

BTW, Thanks for the cool plugin.
