### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by alefranz** [KnisterPeter/vscode-github#59]
It would be nice to make it GitHub Enterprise compatible.

I guess ideally you need the ability to set a token for each hostname.

**Comment by KnisterPeter** [comment]
I have no access to github enterprise so it would not be easy for me to implement this. Could you explain your requirements in a bit more depths?

**Comment by alefranz** [comment]
GitHub Enterpise is GitHub on premises, so instead of github.com the url is custom.
Also, as the users are totally independent from the one on github.com, you have a different user and access token.

So practically to support GitHub enterprise, you need to provide the url of your GitHub Enterprise server and your access token.

Ideally this should be in addition to your github.com token (as you will probably use both)and potentially you could have more than one GitHub Enterprise servers (e.g. a freelancer working for multiple companies, maybe not really common).

I can probably give it a go over the weekend if you like.

**Comment by KnisterPeter** [comment]
Sounds great for me. Do you think it would be okay to store the github url and github access-token in the project folder/config if github enterprise should be used?

That way a project could decide to use github enterprise but it would not be possible to use both at the same time (which should be okay IMHO).

This would also keep the general setup simple for most users and the UI (which is only basic in vscode) as well.

**Comment by ProLoser** [comment]
I think the way it works now, you are assuming a URL is not github because it's not `github.com`. What you could do is allow me to set an additional token that is associated with a specific hostname or base URI. That way I can do something like creating a token for `*github.sony.com*`. Your plugin would then check the remote URL and see if it matches either a: `github.com` or b: any stored token hosts.

@KnisterPeter what do you think? Typically it's not something I want to decide on a project-by-project basis, I'd rather you just use the default remote URL I have configured. It may not be unusual to push to multiple remote servers (such as public and private servers) but I don't think people are going to manage their project (such as issues and pull requests) on both a public Github instance AND a private one.

**Comment by KnisterPeter** [comment]
@ProLoser Sounds reasonable. I like the idea and will restructure the access-token handling so github.com is just one possible domain to store a token for. Then it will be easy to add enterprise support.

**Comment by KnisterPeter** [comment]
@ProLoser I have no access to github enterprise, so I cannot test this in any way. I guess there is the requirement to talk to the api of the onpremise installation. Normaly this is api.github.com. Does this need to be configurable?

**Comment by KnisterPeter** [comment]
In addition what does the repository urls can look like?
For github this is a valid url `git@github.com:KnisterPeter/vscode-github.git`. Does just the hostname change?

**Comment by ProLoser** [comment]
A snippet taken from my `.git/config` in the repo
```
[remote "origin"]
        url = https://github.myteam.example.com/repo-org/repo-name
```
There don't appear to be any other urls on the repo. I put `myteam` because our subdomain is actual longer than normal and wouldn't want the regex to be too restrictive (I'd honestly just do substring matching).

According to the [enterprise api docs](https://developer.github.com/enterprise/2.8/guides/getting-started/) I'm guessing the API is identical aside from the host:

```
curl http(s)://[hostname]/api/v3/users/defunkt
```

For my company, I'd specify `https://github.myteam.example.com` to roughly be the server, and you should be able to work off of that accordingly. The only time I would think sub-domains come into play are for things like gh-pages which on _our_ servers are actually `https://github.myteam.example.com/pages/*`. No idea if enterprise can configure this to be another sub-domain, but regardless it I'm not too worried about that stuff vs issues/pull-requests, etc.

**Comment by KnisterPeter** [comment]
Released in 0.14.
Any feedback if its working is appreciated.

**Comment by ProLoser** [comment]
I pasted `https://mydomain.com` for the host and the token. But when I go to browse issues I get an `unauthorized` error.

**Comment by ProLoser** [comment]
Hmm I think it worked when I dropped the `https://` part. Is this by design?
