### ISSUE TITLE
Commands don't work when the root of the workspace isn't a git repo

### ISSUE THREAD

**Issue by levity** [KnisterPeter/vscode-github#851]
I open a folder that contains multiple git repos in VS Code. I open a file in one of these repos and run e.g. "Github: Browse current file" on that file. 

I get the error: "Error: Command failed with exit code 128: git rev-parse --show-toplevel fatal: not a git repository (or any of the parent directories): .git"

Is there any workaround for this? Ideally the extension would be smart enough to traverse up the folder tree from the file in question to figure out which repo to use, rather than depending on the workspace root.

**Comment by KnisterPeter** [comment]
Hi @levity, this is currently not possible.
It's a good idea but that wouldn't work for most of the commands and workflows in this extension since they are not targeting a single file.
I would propose to create a configuation entry which defines the git root folder. This should default to workspace root if not set otherwise. Feel free to provide a pull request for this.
